version: 3
image: ubuntu:16.04
stages:
  - test
  - build
  - deploy

job_build_std:
  stage: build
  job_type: image_build
  dockerfile_path: /Dockerfile
  build_dir: app/
  only:
    branches:
      - master
    tags:
      - .*

job_build_lite:
  stage: build
  job_type: lite_image_build
  except:
    branches:
    - .*
    tags:
    - .*
  compile:
    build_dir: /
    cache: true
    dockerfile_path: Dockerfile.compile
  extract:
    - /usr/bin/application
  package:
    build_dir: /
    cache: true
    dockerfile_path: Dockerfile.package

job_test:
  stage: test
  job_type: test
  only:
    branches:
      - .*
  pull_request: true
  env:
    - MYSQL_USERNAME="root"
    - MYSQL_PASSWORD=""
    - MYSQL_INSTANCE_NAME="test"
  image: daocloud/ci-python:2.7
  script:
    - pip install -r requirements.txt
    - nosetests test.py --with-xunit --xunit-file=$TEST_RESULT
    - coverage run --branch test.py
    - coverage xml -o $TEST_COVERAGE test.py
    - cat $TEST_RESULT
    - cat $TEST_COVERAGE
  services:
    - mysql
